import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.scss";
import { CustomHeader } from "../../components/CustomHeader";
import { getServerSession, Session } from "next-auth";
import { useState } from "react";
import NextAuthProvider from "../providers";
import { authOptions } from "@/src/libs/next-auth-options";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: Session | null = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <CustomHeader session={session} />
          <div className="h-14" />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
